### ISSUE TITLE
Problem in build project

### ISSUE THREAD

**Issue by mehrdaddolatkhah** [Ezike/Baking-App-Kotlin#48]
Hello,
thank you for your great job. when I try to build project I got this error:

This version of the Android Support plugin for IntelliJ IDEA (or Android Studio) cannot open this project, please retry with version 4.2 or newer.

-- I use android studio 4.1 version (is there available android studio 4.2 in this time?)

**Comment by Ezike** [comment]
> Hello,
> thank you for your great job. when I try to build project I got this error:
> 
> This version of the Android Support plugin for IntelliJ IDEA (or Android Studio) cannot open this project, please retry with version 4.2 or newer.
> 
> -- I use android studio 4.1 version (is there available android studio 4.2 in this time?)

Hello, sorry I'm just seeing this. You would need Android studio 4.2 canary 7 to build the project successfully. Optionally, you can downgrade the android gradle plugin version to the one you have in your Android studio build.

Click [here](https://developer.android.com/studio/preview) to download the latest Android studio preview:
